version: '3.6'

services:
  srvdb:
    image: postgres
    container_name: srvdb
    hostname: srvdb
    environment:
      POSTGRES_USER: consultas
      POSTGRES_DB: consultas
      POSTGRES_PASSWORD: QueryConSql.pwd
    ports:
      - 5432:5432
    networks:
      - demo_kcs_net

  srvwildfly:
    image: myapp
    container_name: srvwildfly
    hostname: srvwildfly
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - srvdb
    networks:
      - demo_kcs_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: info@jtux.ec
      PGADMIN_DEFAULT_PASSWORD: clave
    ports:
      - 5050:80
    depends_on:
      - srvdb
    networks:
      - demo_kcs_net

  apilayer:
    image: nginx:latest
    container_name: apilayer
    hostname: apilayer
    ports:
      - "3000:80"
    depends_on:
      - srvwildfly
    networks:
      - demo_kcs_net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  demo_kcs_net:
